spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/atletic_benilloba_eoi
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver
    web:
        resources:
            static-locations: file:public
   
logging.level.org.springframework.jdbc.core: TRACE
